version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 1575b266c8da9a3ef59e4e67d55a4a373ebec0f26f87fed6540816d0a66508ec
    docker:
      - image: circleci/node:carbon

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build the app
      - run:
          name: Build the app
          command:
            npm run build

      # run tests and post coverage to cc
      # - run:
      #     name: Run tests
      #     command: |
      #       ./cc-test-reporter before-build
      #       npm test
      #       ./cc-test-reporter after-build --exit-code $?
